version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  php: bigcommerce/internal-php@volatile

define: &php_min "8.1"

jobs_default: &jobs_default
  e:
    name: php/php
    php-version: << matrix.php-version >>
  matrix:
    parameters:
      php-version: [ *php_min, "8.2" ]

jobs:
  cs-fixer:
    executor:
      name: php/php
      php-version: *php_min
    steps:
      - ci/pre-setup
      - php/composer-install
      - run: ./vendor/bin/php-cs-fixer fix --diff --dry-run -v

workflows:
  version: 2
  full:
    jobs:
      - php/phpunit-tests:
          <<: *jobs_default
          minimum_coverage: 60
      - php/static-analysis:
          <<: *jobs_default
          generate_ide_helper: false
      - cs-fixer

